### ISSUE TITLE
random number generation

### ISSUE THREAD

**Issue by Sandman83** [libmir/mir-random#116] opened 2019-01-20 00:21 UTC
Hi there, 
I'm developing a time-reaction propagator for physical simulations based on the Gillespie algorithm. 
See https://code.dlang.org/packages/gillespied. 
I would like to provide an optional dependency on mir.random. 
Managed to do this, however, while testing I found that for a particular case, test results don't fit the expected results. 
See https://bitbucket.org/Sandman8/gillespied/issues/1/bug-with-real-type
The tests I drive include 
std.random of phobos and mir.random
both for types float, double, real and size_t. 
The test fails only for the combination of mir.random & real. 
This is the reason, why I'm writing here. However, not sure, where the bug really is. Maybe you could have a look at this.

**Comment by Sandman83** [comment] 2019-01-20 13:31
Oh... yes. Should be open by now.

**Comment by 9il** [comment] 2019-01-27 08:17
@Sandman83 Could you please make the error and issue more informative: some math interpretation and error values. Mir Random may generate all possible values of random numbers including subnormal numbers (Phobos can't and is quite limited). The simple histogram shows that random numbers are generated properly. In the same time `real` may have other issues.

**Comment by Sandman83** [comment] 2019-01-27 19:17
Argh... interesting...
I was refactoring my code for answering your question. And suddenly the error was gone. You can also see https://bitbucket.org/Sandman8/gillespied/commits/fdda932
Having this, I can now provide an abstracted example and a more concrete question, see attached file 
[app.d.txt](https://github.com/libmir/mir-random/files/2800390/app.d.txt)

If you run the main, you see the 10 least entries of each filled arrays. 
Only in case of the 'real' typed array and the usage of mir.random, there is a difference of order 15 in the entries. Even more, this effect is gone, if the array (and so, the number of samples) is chosen smaller. 
Why it is so? Is this effect intended?

**Comment by 9il** [comment] 2019-01-27 20:02
Yeah, 99% it is a bug with real. 1% - it is Mersenne Twister effect on Mir's algorithm. Thanks for the test case.

btw, `[a, b].sum` looks ~x1000 times slower then a+b because of [a, b] calls GC allocation (lock threads, may start GC and other things)

**Comment by 9il** [comment] 2019-01-27 20:16
confirmed with pcg and xoshiro

**Comment by Sandman83** [comment] 2019-01-27 20:19
Ah... cool...

**Comment by Sandman83** [comment] 2019-01-27 20:43
So... if the bug is with the type, should another issue be opened at issues.dlang.org? But how to argument there, if with std.random the bug is not visible?

**Comment by 9il** [comment] 2019-01-27 20:48
the type is ok) I found the problem, I mean it is a bug with implementation for real

**Comment by Sandman83** [comment] 2019-01-27 20:48
ah :)

**Comment by 9il** [comment] 2019-01-27 21:14
Fixed in v2.2.2

**Closed by 9il** 2019-01-27 21:14 UTC
Labels: bug
